name: latest-weekly
on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v4
      - name: Jenkins Weekly version
        id: update
        uses: jenkins-infra/jenkins-version@0.6.3
        with:
          version-identifier: latest
      - name: Process Version
        id: process
        run: |
          SUFFIX=jdk17
          FULL_VERSION=jenkins/jenkins:${{ steps.update.outputs.jenkins_version }}-${SUFFIX}
          echo $FULL_VERSION
          sed -i 's|FROM .*|FROM '"${FULL_VERSION}"'|' Dockerfile
      - name: Calculate Diff
        id: diff
        run: |
          if [[ $(git diff --stat) != '' ]]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2.1.0
        id: generate-token
        if: ${{ steps.diff.outputs.changed == 'true' }}
        with:
          app_id: ${{ secrets.JENKINS_ADMIN_APP_ID }}
          private_key: ${{ secrets.JENKINS_ADMIN_APP_PRIVKEY }}
      - name: Create Pull Request
        id: cpr
        if: ${{ steps.diff.outputs.changed == 'true' }}
        uses: peter-evans/create-pull-request@c5a7806660adbe173f04e3e038b0ccdcd758773c # v6.1.0
        with:
          commit-message: 'feat(deps): bump jenkins weekly to ${{ steps.update.outputs.jenkins_version }}'
          signoff: false
          title: 'feat(deps): bump jenkins weekly to ${{ steps.update.outputs.jenkins_version }}'
          branch: latest-weekly
          token: ${{ steps.generate-token.outputs.token }}
